services:
  phpunit:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    entrypoint:
      - vendor/bin/phpunit
      - tests
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
      PHP_IDE_CONFIG: serverName=Docker
    depends_on:
      - redis
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'test-redis:/data'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
volumes:
  test-redis: